- name: Install EPEL repository (if not already installed)
  yum:
    name: epel-release
    state: present



#- name: Add Grafana YUM repository
#  yum_repository:
#    name: grafana
#    description: Grafana Repository
#    baseurl: https://packages.grafana.com/oss/rpm
#    enabled: yes
#    gpgcheck: yes
#    gpgkey: https://packages.grafana.com/gpg.key

- name: Install Grafana
  yum:
    name: sudo yum install -y https://dl.grafana.com/oss/release/grafana-11.5.2-1.x86_64.rpm
    state: present

- name: Start and enable Grafana service
  service:
    name: grafana-server
    state: started
    enabled: yes

- name: Add Prometheus data source to Grafana
  uri:
    url: "http://localhost:3000/api/datasources"
    method: POST
    user: admin
    password: admin
    body: |
      {
        "name": "Prometheus",
        "type": "prometheus",
        "url": "http://{{ prometheus_server }}:9090",
        "access": "proxy",
        "isDefault": true
      }
    headers:
      Content-Type: "application/json"
    status_code: 200

